# Generated by Django 5.0.6 on 2024-06-27 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_contacto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='proovedor',
            new_name='proveedor',
        ),
    ]
